### ISSUE TITLE
Move linked files in index.html

### ISSUE THREAD

**Issue by serhiicss** [eisenfox/goldmate#2]
Perhaps it is a good idea to move google font links to a stylesheet via import. Also move jquerry link to the bottom of the page before `</body>` tag?

**Comment by eisenfox** [comment]
Ok, you're right, let's do it!

**Comment by eisenfox** [comment]
Could you please do it yourself?

**Comment by serhiicss** [comment]
Sure thing!

**Comment by serhiicss** [comment]
Fixed
